### ISSUE TITLE
CS2 Support

### ISSUE THREAD

**Issue by DaVarga** [thetredev/steamcmd#25]
I wonder if this images supports CS2 dedicated server or if it is planed to do so.

**Comment by thetredev** [comment]
It should *just work* after we get the official updates. As far as I can tell it will be just another CS:GO update.

But yes, in general I plan to support CS2 as well.

**Comment by DaVarga** [comment]
Okay, great. 
Is there a way to host cs2 beta servers right now? There are already commercial hosts who offer cs2 beta servers. As i have  beta access i would like to try to host one myself but documentation about the dedicated server it is kinda limited.

**Comment by thetredev** [comment]
I can have a look, not sure tho.

**Comment by DaVarga** [comment]
Hi, just to keep you updated. I reached out to some hosts, they all seem to use the windows game client since there is no dedicated server available yet. 
Since the game should release soon it is not worth the hustle and might be out of scope anyways. Once the dedicated server arrives im happy to collaborate.

Thank you for your help.

**Comment by DaVarga** [comment]
CS2 released, replacing Global Offensive. But sadly no dedicated server yet.
https://steamcommunity.com/faqs/steam-help/view/5ED2-ED8E-81F4-0C18#commserver
